# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: myagent01

steps:

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.1.4'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Azure subscription 1 (8387394d-454a-4a31-b9cf-b43edde3669e)'
    backendAzureRmResourceGroupName: 'example-resourcesone'
    backendAzureRmStorageAccountName: 'evgdemo'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'dev'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Azure subscription 1 (8387394d-454a-4a31-b9cf-b43edde3669e)'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Azure subscription 1 (8387394d-454a-4a31-b9cf-b43edde3669e)'
