# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: myagent01

- task: Terraform@2
  inputs:
    TemplatePath: '$(System.DefaultWorkingDirectory)'
    Arguments: 'init'
    InstallTerraform: true
    UseAzureSub: true
    ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
    ConnectedServiceNameARM: 'Azure subscription 1 (8387394d-454a-4a31-b9cf-b43edde3669e)'
    ManageState: false
